"""remove movement_type from staff

Revision ID: 144bd147a6dd
Revises: 6e13fde77a5c
Create Date: 2026-05-15 15:48:58.732916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '144bd147a6dd'
down_revision: Union[str, Sequence[str], None] = '6e13fde77a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_staff', 'movement_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_staff', sa.Column('movement_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
