"""add_scope_all_to_role_module

Revision ID: 245f64dfed77
Revises: 8144730b5943
Create Date: 2026-01-23 19:32:49.573108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245f64dfed77'
down_revision: Union[str, Sequence[str], None] = '8144730b5943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_module', sa.Column('scope_all', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_module', 'scope_all')
    # ### end Alembic commands ###
