"""security_update_user_and_logs

Revision ID: 437ede102e65
Revises: 7fd80b3bb1fc
Create Date: 2026-01-21 11:34:59.137819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '437ede102e65'
down_revision: Union[str, Sequence[str], None] = '7fd80b3bb1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed drop_table commands for product/customer modules as they were incorrect auto-detections.

    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.drop_column('user_log_login', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_log_login', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    # Note: Removed create_table commands for product/customer modules.
    # ### end Alembic commands ###
