"""Add is_active to core models

Revision ID: 557139a8c157
Revises: 76350099f1f5
Create Date: 2026-05-15 11:38:37.688310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '557139a8c157'
down_revision: Union[str, Sequence[str], None] = '76350099f1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_org_unit', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('core_staff', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('core_staff_position', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_staff_position', 'is_active')
    op.drop_column('core_staff', 'is_active')
    op.drop_column('core_org_unit', 'is_active')
    # ### end Alembic commands ###
