"""add performance indices to staff and units

Revision ID: 5ab725ad6f8a
Revises: 144bd147a6dd
Create Date: 2026-05-15 15:56:03.286098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ab725ad6f8a'
down_revision: Union[str, Sequence[str], None] = '144bd147a6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_core_org_unit_is_active'), 'core_org_unit', ['is_active'], unique=False)
    op.create_index(op.f('ix_core_org_unit_name'), 'core_org_unit', ['name'], unique=False)
    op.create_index(op.f('ix_core_org_unit_parent_id'), 'core_org_unit', ['parent_id'], unique=False)
    op.create_index(op.f('ix_core_staff_email'), 'core_staff', ['email'], unique=False)
    op.create_index(op.f('ix_core_staff_full_name'), 'core_staff', ['full_name'], unique=False)
    op.create_index(op.f('ix_core_staff_is_active'), 'core_staff', ['is_active'], unique=False)
    op.create_index('ix_core_staff_unit_id', 'core_staff', ['org_unit_id'], unique=False)
    op.create_index('ix_core_staff_pos_id', 'core_staff', ['position_id'], unique=False)
    op.create_index(op.f('ix_core_staff_position_is_active'), 'core_staff_position', ['is_active'], unique=False)
    op.create_index(op.f('ix_core_staff_position_name'), 'core_staff_position', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_staff_position_name'), table_name='core_staff_position')
    op.drop_index(op.f('ix_core_staff_position_is_active'), table_name='core_staff_position')
    op.drop_index('ix_core_staff_pos_id', table_name='core_staff')
    op.drop_index('ix_core_staff_unit_id', table_name='core_staff')
    op.drop_index(op.f('ix_core_staff_is_active'), table_name='core_staff')
    op.drop_index(op.f('ix_core_staff_full_name'), table_name='core_staff')
    op.drop_index(op.f('ix_core_staff_email'), table_name='core_staff')
    op.drop_index(op.f('ix_core_org_unit_parent_id'), table_name='core_org_unit')
    op.drop_index(op.f('ix_core_org_unit_name'), table_name='core_org_unit')
    op.drop_index(op.f('ix_core_org_unit_is_active'), table_name='core_org_unit')
    # ### end Alembic commands ###
