"""Add core staff and fixed assets modules

Revision ID: 65ec41c5e5cd
Revises: f51cbafde077
Create Date: 2026-01-27 20:24:17.463506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65ec41c5e5cd'
down_revision: Union[str, Sequence[str], None] = 'f51cbafde077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_asset_group',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_group_id'), 'assets_asset_group', ['id'], unique=False)
    op.create_table('assets_asset_status',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_status_id'), 'assets_asset_status', ['id'], unique=False)
    op.create_table('assets_institution',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_institution_id'), 'assets_institution', ['id'], unique=False)
    op.create_table('core_org_unit',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('acronym', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('general_unit', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['core_org_unit.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_org_unit_external_id'), 'core_org_unit', ['external_id'], unique=True)
    op.create_index(op.f('ix_core_org_unit_id'), 'core_org_unit', ['id'], unique=False)
    op.create_table('core_staff_position',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('position_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_staff_position_external_id'), 'core_staff_position', ['external_id'], unique=False)
    op.create_index(op.f('ix_core_staff_position_id'), 'core_staff_position', ['id'], unique=False)
    op.create_table('assets_area',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['assets_institution.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_area_id'), 'assets_area', ['id'], unique=False)
    op.create_table('core_staff',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name_1', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name_2', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('document_location', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cellphone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('staff_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('movement_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('org_unit_id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['core_org_unit.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['core_staff_position.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_staff_document_number'), 'core_staff', ['document_number'], unique=True)
    op.create_index(op.f('ix_core_staff_external_id'), 'core_staff', ['external_id'], unique=True)
    op.create_index(op.f('ix_core_staff_id'), 'core_staff', ['id'], unique=False)
    op.create_table('assets_act',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('act_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_attachment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('staff_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['core_staff.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_act_act_number'), 'assets_act', ['act_number'], unique=True)
    op.create_index(op.f('ix_assets_act_id'), 'assets_act', ['id'], unique=False)
    op.create_table('assets_fixed_asset',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('old_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('new_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('location_detail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('observations', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_saf', sa.Boolean(), nullable=False),
    sa.Column('is_physically_verified', sa.Boolean(), nullable=False),
    sa.Column('is_decommissioned', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('source_files', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('status_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('org_unit_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('custodian_staff_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['assets_area.id'], ),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['core_staff.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['custodian_staff_id'], ['core_staff.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['assets_asset_group.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['core_org_unit.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['assets_asset_status.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_fixed_asset_id'), 'assets_fixed_asset', ['id'], unique=False)
    op.create_index(op.f('ix_assets_fixed_asset_new_code'), 'assets_fixed_asset', ['new_code'], unique=False)
    op.create_index(op.f('ix_assets_fixed_asset_old_code'), 'assets_fixed_asset', ['old_code'], unique=False)
    op.create_table('assets_asset_act_link',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('act_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['assets_act.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets_fixed_asset.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'act_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets_asset_act_link')
    op.drop_index(op.f('ix_assets_fixed_asset_old_code'), table_name='assets_fixed_asset')
    op.drop_index(op.f('ix_assets_fixed_asset_new_code'), table_name='assets_fixed_asset')
    op.drop_index(op.f('ix_assets_fixed_asset_id'), table_name='assets_fixed_asset')
    op.drop_table('assets_fixed_asset')
    op.drop_index(op.f('ix_assets_act_id'), table_name='assets_act')
    op.drop_index(op.f('ix_assets_act_act_number'), table_name='assets_act')
    op.drop_table('assets_act')
    op.drop_index(op.f('ix_core_staff_id'), table_name='core_staff')
    op.drop_index(op.f('ix_core_staff_external_id'), table_name='core_staff')
    op.drop_index(op.f('ix_core_staff_document_number'), table_name='core_staff')
    op.drop_table('core_staff')
    op.drop_index(op.f('ix_assets_area_id'), table_name='assets_area')
    op.drop_table('assets_area')
    op.drop_index(op.f('ix_core_staff_position_id'), table_name='core_staff_position')
    op.drop_index(op.f('ix_core_staff_position_external_id'), table_name='core_staff_position')
    op.drop_table('core_staff_position')
    op.drop_index(op.f('ix_core_org_unit_id'), table_name='core_org_unit')
    op.drop_index(op.f('ix_core_org_unit_external_id'), table_name='core_org_unit')
    op.drop_table('core_org_unit')
    op.drop_index(op.f('ix_assets_institution_id'), table_name='assets_institution')
    op.drop_table('assets_institution')
    op.drop_index(op.f('ix_assets_asset_status_id'), table_name='assets_asset_status')
    op.drop_table('assets_asset_status')
    op.drop_index(op.f('ix_assets_asset_group_id'), table_name='assets_asset_group')
    op.drop_table('assets_asset_group')
    # ### end Alembic commands ###
