"""Add item_number and external_parent_id

Revision ID: 6e13fde77a5c
Revises: 557139a8c157
Create Date: 2026-05-15 11:55:07.762578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e13fde77a5c'
down_revision: Union[str, Sequence[str], None] = '557139a8c157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_org_unit', sa.Column('external_parent_id', sa.Integer(), nullable=True))
    op.add_column('core_staff_position', sa.Column('item_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_staff_position', 'item_number')
    op.drop_column('core_org_unit', 'external_parent_id')
    # ### end Alembic commands ###
