"""refactor_module_group_fk_to_slug

Revision ID: 787feb4b4620
Revises: 6b84f12b1f38
Create Date: 2026-01-23 17:45:59.211351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '787feb4b4620'
down_revision: Union[str, Sequence[str], None] = '6b84f12b1f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('group_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('module_group_id_fkey'), 'module', type_='foreignkey')
    op.create_foreign_key(None, 'module', 'module_group', ['group_slug'], ['slug'])
    op.drop_column('module', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.create_foreign_key(op.f('module_group_id_fkey'), 'module', 'module_group', ['group_id'], ['id'])
    op.drop_column('module', 'group_slug')
    # ### end Alembic commands ###
