"""unique_constraint_role_module_slugs

Revision ID: 8144730b5943
Revises: 984fe43bd278
Create Date: 2026-01-23 19:25:59.308437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8144730b5943'
down_revision: Union[str, Sequence[str], None] = '984fe43bd278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_module_slugs', 'role_module', ['role_slug', 'module_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_module_slugs', 'role_module', type_='unique')
    # ### end Alembic commands ###
