"""refactor_role_and_role_module_to_slugs

Revision ID: 984fe43bd278
Revises: 787feb4b4620
Create Date: 2026-01-23 18:45:16.116580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '984fe43bd278'
down_revision: Union[str, Sequence[str], None] = '787feb4b4620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_role_slug'), 'role', ['slug'], unique=True)
    op.add_column('role_module', sa.Column('role_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('role_module', sa.Column('module_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('role_module_module_id_fkey'), 'role_module', type_='foreignkey')
    op.drop_constraint(op.f('role_module_role_id_fkey'), 'role_module', type_='foreignkey')
    op.create_foreign_key(None, 'role_module', 'module', ['module_slug'], ['slug'])
    op.create_foreign_key(None, 'role_module', 'role', ['role_slug'], ['slug'])
    op.drop_column('role_module', 'role_id')
    op.drop_column('role_module', 'module_id')
    op.add_column('user_role', sa.Column('role_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('user_role_role_id_fkey'), 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'role', ['role_slug'], ['slug'])
    op.drop_column('user_role', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_role_id_fkey'), 'user_role', 'role', ['role_id'], ['id'])
    op.drop_column('user_role', 'role_slug')
    op.add_column('role_module', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('role_module', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role_module', type_='foreignkey')
    op.drop_constraint(None, 'role_module', type_='foreignkey')
    op.create_foreign_key(op.f('role_module_role_id_fkey'), 'role_module', 'role', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_module_module_id_fkey'), 'role_module', 'module', ['module_id'], ['id'])
    op.drop_column('role_module', 'module_slug')
    op.drop_column('role_module', 'role_slug')
    op.drop_index(op.f('ix_role_slug'), table_name='role')
    op.drop_column('role', 'slug')
    # ### end Alembic commands ###
